// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	models "financial-data-backend-2/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// RepoItf is an autogenerated mock type for the RepoItf type
type RepoItf struct {
	mock.Mock
}

// GetSymbols provides a mock function with given fields: _a0
func (_m *RepoItf) GetSymbols(_a0 context.Context) ([]models.SymbolDocument, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetSymbols")
	}

	var r0 []models.SymbolDocument
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.SymbolDocument, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.SymbolDocument); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.SymbolDocument)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTradesPerSymbol provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *RepoItf) GetTradesPerSymbol(_a0 context.Context, _a1 string, _a2 int, _a3 int64) ([]models.TradeRecord, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for GetTradesPerSymbol")
	}

	var r0 []models.TradeRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int64) ([]models.TradeRecord, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int64) []models.TradeRecord); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.TradeRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int64) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepoItf creates a new instance of RepoItf. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepoItf(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepoItf {
	mock := &RepoItf{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
